spring:
  application:
    name: product-ms
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true        
  datasource: 
    username: ibm
    password: ibm
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  security:
    basic:
      enabled: false    user:      name: admin
      password: admin
  
server:
  port: 8301
  
management:
  endpoints:
    web:
      exposure:
        include: '*'  
        
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.uri:http://192.168.99.100:8100/eureka}
      
feign:
  hystrix:
    enabled: true
    
